// Salary Components
export const SALARY_COMPONENTS_FETCH_REQUEST = 'SALARY_COMPONENTS_FETCH_REQUEST';
export const SALARY_COMPONENTS_FETCH_SUCCESS = 'SALARY_COMPONENTS_FETCH_SUCCESS';
export const SALARY_COMPONENTS_FETCH_FAILED = 'SALARY_COMPONENTS_FETCH_FAILED';

export const SALARY_COMPONENT_CREATE_SUCCESS = 'SALARY_COMPONENT_CREATE_SUCCESS';
export const SALARY_COMPONENT_CREATE_FAILED = 'SALARY_COMPONENT_CREATE_FAILED';

export const SALARY_COMPONENT_EDIT_SUCCESS = 'SALARY_COMPONENT_EDIT_SUCCESS';
export const SALARY_COMPONENT_EDIT_FAILED = 'SALARY_COMPONENT_EDIT_FAILED';

export const SALARY_COMPONENT_DELETE_SUCCESS = 'SALARY_COMPONENT_DELETE_SUCCESS';
export const SALARY_COMPONENT_DELETE_FAILED = 'SALARY_COMPONENT_DELETE_FAILED';

// Designations
export const DESIGNATIONS_FETCH_REQUEST = 'DESIGNATIONS_FETCH_REQUEST';
export const DESIGNATIONS_FETCH_SUCCESS = 'DESIGNATIONS_FETCH_SUCCESS';
export const DESIGNATIONS_FETCH_FAILED = 'DESIGNATIONS_FETCH_FAILED';

export const DESIGNATION_CREATE_SUCCESS = 'DESIGNATION_CREATE_SUCCESS';
export const DESIGNATION_CREATE_FAILED = 'DESIGNATION_CREATE_FAILED';

export const DESIGNATION_EDIT_SUCCESS = 'DESIGNATION_EDIT_SUCCESS';
export const DESIGNATION_EDIT_FAILED = 'DESIGNATION_EDIT_FAILED';

export const DESIGNATION_DELETE_SUCCESS = 'DESIGNATION_DELETE_SUCCESS';
export const DESIGNATION_DELETE_FAILED = 'DESIGNATION_DELETE_FAILED';

// sEmployee
export const EMPLOYEES_FETCH_REQUEST = 'EMPLOYEES_FETCH_REQUEST';
export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS';
export const EMPLOYEES_FETCH_FAILED = 'EMPLOYEES_FETCH_FAILED';

export const EMPLOYEE_CREATE_SUCCESS = 'EMPLOYEE_CREATE_SUCCESS';
export const EMPLOYEE_CREATE_FAILED = 'EMPLOYEE_CREATE_FAILED';

export const EMPLOYEE_EDIT_SUCCESS = 'EMPLOYEE_EDIT_SUCCESS';
export const EMPLOYEE_EDIT_FAILED = 'EMPLOYEE_EDIT_FAILED';

export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS';
export const EMPLOYEE_DELETE_FAILED = 'EMPLOYEE_DELETE_FAILED';